name: Test Makefile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
      - run: make all

  test-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
      - run: make all
